name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout Code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version:  ${{ vars.JAVA_VERSION }}

      - name: Make gradle Executable
        run: chmod +x gradlew

      - name: Run Tests
        run: ./gradlew test

      #----- sonarCloud scan -------
      - name: Sonar Scan
        run: ./gradlew sonar
        env:
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN }}

      # ------ TruffleHog secret Scan---------
      - name: TruffleHog scan
        uses: trufflesecurity/trufflehog@main
        with:
          path: .
      #-------- Build project-----------
      - name: Build project
        run: ./gradlew build

      #----------Login to docker hub------
      - name: Login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #------------------Build docker image ---------
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ vars.DOCKER_IMAGE_NAME }} .

      #---------------Push Docker images-----------
      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ vars.DOCKER_IMAGE_NAME }}
